modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "hexportation"
version = "${version}"
displayName = "Hexportation"
logoFile = "icon.png"
authors = "kineticcat"
description = '''
Hexportation addon for Hex Casting
'''

[[dependencies.hexportation]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexportation]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexportation]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexportation]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingDependencyVersion},)"
ordering = "NONE"
side = "BOTH"
